# 2026-05-31: Production payment channel environment template.
# Fill these values from the merchant console or secret manager before starting container-manager.

# Alipay refund channel.
$env:MANAGER_ALIPAY_ENABLED = "true"
$env:MANAGER_ALIPAY_ENVIRONMENT = "production"
$env:MANAGER_ALIPAY_SERVER_URL = "https://openapi.alipay.com/gateway.do"
$env:MANAGER_ALIPAY_APP_ID = "<ALIPAY_APP_ID>"
$env:MANAGER_ALIPAY_MERCHANT_PRIVATE_KEY = "<ALIPAY_MERCHANT_PRIVATE_KEY>"
$env:MANAGER_ALIPAY_PUBLIC_KEY = "<ALIPAY_PUBLIC_KEY>"
$env:MANAGER_ALIPAY_SIGN_TYPE = "RSA2"
$env:MANAGER_ALIPAY_CHARSET = "UTF-8"
$env:MANAGER_ALIPAY_FORMAT = "json"
$env:MANAGER_ALIPAY_ALLOW_ORDER_NO_AS_OUT_TRADE_NO = "false"

# WeChat Pay refund channel.
$env:MANAGER_WECHAT_ENABLED = "true"
$env:MANAGER_WECHAT_ENVIRONMENT = "production"
$env:MANAGER_WECHAT_MCH_ID = "<WECHAT_MCH_ID>"
$env:MANAGER_WECHAT_APP_ID = "<WECHAT_APP_ID>"
$env:MANAGER_WECHAT_API_V3_KEY = "<WECHAT_API_V3_KEY>"
$env:MANAGER_WECHAT_MERCHANT_SERIAL_NO = "<WECHAT_MERCHANT_SERIAL_NO>"
$env:MANAGER_WECHAT_PRIVATE_KEY_PATH = "<ABSOLUTE_PATH_TO_APICLIENT_KEY_PEM>"
$env:MANAGER_WECHAT_REFUND_NOTIFY_URL = "<HTTPS_REFUND_NOTIFY_URL>"
$env:MANAGER_WECHAT_ALLOW_ORDER_NO_AS_OUT_TRADE_NO = "false"
